language: r
cache: packages

env:
  global:
    - secure: "Fo0DB0Zc5VB/l5bvQcWdH6WWavSTq1PF76DAAQL7iyYaIfKppkIhfxjN0L/GEcijnzrcQowqKE49eISG1u2BactR80DwkgpavH7wJ6OeJ0/8h2MMhJjwb/aA9WAyHzLPVXyrv8+7En0bcbxojNxKse/YBWeXCfexJpyV5d+P2PSyuSkR6p2mYZiZ46E6aOVSsheEvnbabjDhveosxZY/PJ5PMBR0roCwBtHsQPZ/wLYLALZsdqAkpBD2KFCkMr7ufbvMmubrbIRfP/OnPDOd3xhk3oYhRkCyA81vfyrYvhy30CiEYeybDcWz18MovmB0EkyM8K2nmYH9U64lV4hEeA1tOgVhK/7FUPkZu0DUxhaXv3WNkyiH2gBP8tSZQ7AGd7QZ6/hhaNiAjLBj9vFtgmUmk8JKy9tSkx1dyk8WK0dMmVfaAgNbani+m+Qx9s8HyOXp+HsIUiDCw5xKJlx463uJ9kn9k66ttQKwDB9dFf62GbhqoacJ8TMpewOB0azy2+ixV2aWLwIh55MDEhF+jkuwVK7sdjrFNHxnix46atQ43C+GB0pOkSHFCKz1kPaz4do3pxEu8Z6MQ+ujdf06PuxuviU1TFKH+tzwEIXSvhuocJCs132F41PZo3dyRh/dDhbAUUU84KlYCJHlKJb3GXSLOEEmiT1wlJsP34G14EY="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
